apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: core
  name: core
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: core
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: core
    spec:
      containers:
      - env:
        - name: TEST_ENV
          value: {{ .Values.svc.api.test_env }}
        # TODO: verify URL when image pushed
        image: {{ .Values.image_registry_url }}/api:{{ .Values.image_tag }}
        imagePullPolicy: Always
        name: site-directory-core
        ports:
        - containerPort: 4747
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
