apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: core
  name: core
spec:
  type: NodePort
  ports:
  - name: "4747"
    port: 4747
    targetPort: 4747
  selector:
    io.kompose.service: core
status:
  loadBalancer: {}